# Generated by Django 6.0.6 on 2026-06-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicenote',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
